import { GoogleGenerativeAI } from "@google/generative-ai"; // ✅ correct import
import { Student, Feedback, CareerQuestion } from "../types";

// ✅ Get API key from .env (must start with VITE_)
const apiKey = import.meta.env.VITE_GEMINI_API_KEY;

// ✅ Initialize Gemini AI client
const genAI = new GoogleGenerativeAI(apiKey);

const geminiService = {
  generateContent: async (params: {
    model: string;
    contents: string | any;
    config?: { systemInstruction?: string };
  }) => {
    try {
      const model = genAI.getGenerativeModel({ model: params.model });
      const result = await model.generateContent({
        contents: params.contents,
      });
      return result.response; // ✅ return the response object
    } catch (err) {
      console.error("Gemini API error:", err);
      throw err;
    }
  },
};

// ✅ Academic Advice
export const getAcademicAdvice = async (prompt: string): Promise<string> => {
  try {
    const response = await geminiService.generateContent({
      model: "gemini-2.0-flash",
      contents: [
        {
          role: "user",
          parts: [
            {
              text: `${prompt}\n\nYou are an AI Academic Advisor. Provide professional, encouraging, and educational advice.\n\n*Disclaimer: This advice is generated by an AI and should be used as a supplementary resource.*`,
            },
          ],
        },
      ],
    });
    return response.text();
  } catch (error) {
    console.error("Error fetching academic advice:", error);
    return "Sorry, I encountered an error while generating advice.";
  }
};

// ✅ Mentor Session Prep
export const getSessionPrepTips = async (student: Student): Promise<string> => {
  const prompt = `
Student Profile:
- Name: ${student.name}
- Major: ${student.major}
- Strengths: ${student.strengths.join(", ")}
- Weakness Areas: ${student.weaknesses.join(", ")}
- Recent Performance: ${student.performanceData
    .slice(-3)
    .map((p) => `${p.subject}: ${p.score}%`)
    .join("; ")}

Generate a structured mentor prep plan under:
### Key Discussion Points
### Potential Questions to Ask
### Suggested Activities
`;

  try {
    const response = await geminiService.generateContent({
      model: "gemini-2.0-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    });
    return response.text();
  } catch (error) {
    console.error("Error fetching session prep tips:", error);
    return "Sorry, I couldn't generate preparation tips.";
  }
};

// ✅ Career Insights
export const getCareerInsights = async (
  answers: { [key: string]: string },
  questions: CareerQuestion[]
): Promise<string> => {
  const formattedAnswers = questions
    .map((q) => {
      let answerText = answers[q.id] || "Not answered";
      if (q.type === "MCQ" && q.options) {
        answerText = q.options[parseInt(answerText)] || answerText;
      }
      return `Question: ${q.text}\nAnswer: ${answerText}`;
    })
    .join("\n\n");

  const prompt = `
A student has completed a career assessment. Analyze their answers and create a Markdown report including:
1. Key themes
2. 2-3 matching career paths
3. Skill development suggestions
4. 3 concrete next steps.

Student's Answers:
${formattedAnswers}
`;

  try {
    const response = await geminiService.generateContent({
      model: "gemini-2.0-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    });
    return response.text();
  } catch (error) {
    console.error("Error fetching career insights:", error);
    return "Sorry, I couldn't generate career insights.";
  }
};

// ✅ Feedback Analysis
export const analyzeFeedbackForAdmin = async (
  feedback: Feedback[],
  mentorName?: string
): Promise<string> => {
  const intro = mentorName
    ? `Analyze the following anonymized student feedback for mentor: ${mentorName}.`
    : `Analyze the following anonymized student feedback for the mentoring program.`;

  const prompt = `
${intro}

Feedback Data:
${feedback
  .map((f) => `- Rating: ${f.rating}/5, Comment: "${f.comment}"`)
  .join("\n")}

Generate a Markdown report with:
#### Strengths
#### Areas for Improvement
#### Actionable Suggestions
`;

  try {
    const response = await geminiService.generateContent({
      model: "gemini-2.0-flash",
      contents: [{ role: "user", parts: [{ text: prompt }] }],
    });
    return response.text();
  } catch (error) {
    console.error("Error analyzing feedback:", error);
    return "Could not analyze feedback at this time.";
  }
};
